config/routes.rb
Rails.application.routes.draw do
  root 'collections#index'

  get 'collections/all' => 'pages#index'

  get 'pages/new'

  get 'pages/create'

  get 'pages/show'

  get 'pages/update'

  get 'pages/destroy'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  resources :users, except: [:new]
  resources :collections, :images
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :images

  validates :user_id, :title, :description, presence: true
  validates :title, length: { minimum: 5, maximum: 50 }
  validates :description, length: { minimum: 10 }
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :collection
  belongs_to :user

  VALID_URL = /https?:\/\/[\S]+/

  validates :link, presence: true, length: { minimum: 5 }, format: { with: VALID_URL }
  validates :collection_id, :picture, presence: true

  has_attached_file :picture, styles: { medium: "300x300>" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/models/session.rb
class Session < ActiveRecord::Base
	def self.sweep(time = 1.hour)
    if time.is_a?(String)
      time = time.split.inject { |count, unit| count.to_i.send(unit) }
    end
 
    delete_all "updated_at < '#{time.ago.to_s(:db)}'"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collections, dependent: :destroy
  has_many :images, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 5 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to root_path
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:edit, :update, :destroy, :show]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @top_collections = Collection.last(6)
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user

    if @collection.save
      flash[:success] = "Collection created"
      redirect_to collection_path(@collection)
    else
      render 'new'
    end
  end

  def show
    @collection = Collection.find(params[:id])

    @collection_images = @collection.images.paginate(page: params[:page], per_page: 3)
  end

  def edit

  end

  def update
    if @collection.update(collection_params)
      flash[:success] = 'Collection Updated!'
      redirect_to collection_path
    else
      render 'edit'
    end
  end

  def destroy
    @collection = Collection.find(params[:id])

    @collection.destroy

    redirect_to collections_path
  end

  private
    def collection_params
      params.require(:collection).permit(:title, :description, :image)
    end

    def set_collection
      @collection = Collection.find(params[:id])
    end

    def require_same_user
      if current_user != @collection.user and !current_user.admin?
        flash[:danger] = 'You can only edit or delete your own collections'
        redirect_to root_path
      end
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    if current_user.collections.count < 1
      flash[:danger] = 'You must create collection before.'
      redirect_to root_path
    else
      @image = Image.new
    end
  end

  def create
    @image = Image.new(image_params)

    @image.user = current_user

    if @image.save
      flash[:success] = 'Photo attached!'
      redirect_to collection_path(image_params[:collection_id])
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @image.update(image_params)
      flash[:success] = 'Image updated!'
      redirect_to collection_path(image_params[:collection_id])
    else
      render 'edit'
    end
  end

  def destroy
    @image.destroy

    redirect_to collection_path(@image.collection)
  end

  private
    def image_params
      params.require(:image).permit(:link, :picture, :collection_id)
    end

    def set_image
      @image = Image.find(params[:id])
    end

    def require_same_user
      if current_user != @image.user and !current_user.admin?
        flash[:danger] = 'You can only edit or delete your own images'
        redirect_to root_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @collections = Collection.paginate(page: params[:page], per_page: 9)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Something wrong!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have logged out'

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_user, only: [:edit]
  before_action :require_admin, only: [:destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 9)
  end

  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to \"Media Collection\", #{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Profile is updated!'
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user_collections = @user.collections.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user = User.find(params[:id])

    @user.destroy
    flash[:danger] = 'Account and all collections by user deleted!'
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = 'Access denied!'
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = 'Only admin user can perform that action'
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 40 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = 'https://secure.gravatar.com/avatar/' + gravatar_id.to_s + '?s=' + size.to_s
    image_tag(gravatar_url, alt: user.username, class: 'img-responsive')
  end

  def user_info
    user = User.find(session[:user_id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/collections/_collections.html.erb
<% obj.each_slice(3) do |collections| %>
    <div class="row">
      <% collections.each do |collection| %>
          <div class="col-md-4 col-sm-6">
            <div class="well shadow">
              <h3 class="text-center"><%= link_to collection.title, collection_path(collection) %></h3>
              <% if collection.images.count > 0 %>
                <%= link_to image_tag(collection.images.first.picture.url, class: 'img-responsive'), collection_path(collection) %>
              <% else %>
                <%= image_tag 'https://upload.wikimedia.org/wikipedia/ru/a/ac/No_image_available.svg', class: 'img-responsive' %>
              <% end %>
              <hr />
              <small>
                <strong>Created by: </strong><%= link_to collection.user.username, user_path(collection.user) if collection.user %>
                <%= time_ago_in_words(collection.created_at) %> ago <br />
                Updated <%= time_ago_in_words(collection.updated_at) %> ago
              </small>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Type name of your new collection' %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: 10, placeholder: 'Simple description for your new collection' %>
      </div>
    </div>
    <div class="col-md-12">
      <p class="text-center">
        <%= f.submit 'Submit', class: 'btn btn-success' %>
      </p>
    </div>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div class="container">
  <h1>Edit Collection</h1>

  <%= render 'form' %>

  <p class="text-center">
    [<%= link_to 'Cancel', collection_path %>]
  </p>
</div>

app/views/collections/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center" id="top-collections">Newest Collections</h2>
    </div>
  </div>
  <%= render 'collections', obj: @top_collections %>
</div>

app/views/collections/new.html.erb
<div class="container">
  <h1 class="text-center">Create New Collections</h1>

  <%= render 'layouts/errors', obj: @collection %>

  <%= render 'form' %>

  <p class="text-center">
    [<%= link_to 'Back', root_path %>]
  </p>
</div>

app/views/collections/show.html.erb
<div class="container">
  <h1><%= @collection.title %></h1>
  <div class="well">
    <p class="lead">
      Description: <%= simple_format(@collection.description) %>
    </p>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <p><strong>Author of collection: </strong><%= link_to @collection.user.username, user_path(@collection.user) %></p>
        <p>User have a <%= pluralize(@collection.user.collections.count, 'collection') %> and <%= pluralize(@collection.user.images.count, 'image') %></p>
        <% if logged_in? and current_user == @collection.user %>
          <p><%= link_to fa_icon("plus", text: "Add image to collection"), new_image_path({ id: @collection.id }), method: :get, class: 'btn btn-warning', id: @collection.id %></p>
        <% end %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="row">
        <% @collection_images.each do |pic| %>
          <div class="col-md-4">
            <div class="well">
              <div class="row">
                <div class="col-md-12">
                  <p>
                    <%= link_to image_tag(pic.picture, class: 'img-responsive'), pic.picture.url, 'data-toggle' => 'lightbox', 'data-title' => @collection.title, 'data-footer' => pic.link %>
                  </p>
                </div>
                <div class="col-md-12">
                  <p>
                    <%= link_to truncate(pic.link, length: 50), pic.link %>
                  </p>
                </div>
                <% if logged_in? and (current_user == @collection.user || current_user.admin?) %>
                  <div class="col-md-12">
                    <p>
                      <%= link_to fa_icon("pencil"), edit_image_path(pic), class: 'btn btn-xs btn-primary' %> <%= link_to fa_icon("trash-o"), image_path(pic), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
                    </p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div align="center">
        <%= will_paginate @collection_images %>
      </div>
    </div>
    <% if logged_in? && (current_user == @collection.user || current_user.admin?) %>
      <div class="col-md-12">
        <p>Actions for collection</p>
        <p>
          <%= link_to fa_icon("pencil", text: "Edit Collection"), edit_collection_path(@collection), class: 'btn btn-primary' %>
          <%= link_to fa_icon("trash-o", text: "Delete Collection"), collection_path(@collection), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </p>
      </div>
    <% end %>
  </div>
  <br />
</div>

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <div class="row">
    <div class="col-md-6 form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', placeholder: 'URL (format of link http://ya.ru)' %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :picture %>
      <%= f.file_field :picture %>
    </div>
    <%= f.hidden_field :collection_id, value: params[:id] ? params[:id] : params[:image][:collection_id] %>
    <div class="col-md-12">
      <p class="text-center">
        <%= f.submit(@image.new_record? ? 'Add image' : 'Update', class: 'btn btn-success') %>
      </p>
      <p class="text-center">
        [<%= link_to 'Back', root_path %>]
      </p>
    </div>
  </div>
<% end %>

app/views/images/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit image</h1>

  <%= render 'form' %>
</div>

app/views/images/new.html.erb
<div class="container">
  <h1 class="text-center">Add new image to collection</h1>

  <%= render 'layouts/errors', obj: @image %>

  <%= render 'form' %>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <h4 class="alert alert-danger">
    <% obj.errors.full_messages.each do |error| %>
      <p>- <%= error %></p>
    <% end %>
  </h4>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div id="info">
    <p class="lead text-center">Using photos from <a href="https://pexels.com" target="_blank">pexels</a></p>
    <p class="text-center">Copyright &copy; 2016. All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <h4 class='alert alert-<%= "#{name}" %> flash'><%= msg %></h4>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Media Collection', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller] == 'pages' && params[:action] == 'index' ? 'active' : '' %>"><%= link_to 'All collections', collections_all_path %></li>
        <% if logged_in? %>
          <li class="<%= params[:controller] == 'users' && params[:action] == 'index' ? 'active' : '' %>"><%= link_to 'All Users', users_path %></li>
        <% end %>
      </ul>
      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= params[:controller] == 'collections' && params[:action] == 'new' ? 'active' : '' %>"><%= link_to 'Add new collection', new_collection_path %></li>
          <li class="dropdown <%= params[:controller] == 'users' and (params[:action] == 'show' or params[:action] == 'edit') ? 'active' : '' %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <%= "(admin)" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View', user_path(current_user) %></li>
              <li><%= link_to 'Edit', edit_user_path(current_user) %></li>
            </ul>
          </li>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign up', signup_path %></li>
          <li><%= link_to 'Log in', login_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Media Collection</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= debug(params) if Rails.env.development? %>

    <%= render 'layouts/navbar' %>

    <div class="jumbotron">
      <h1 class="text-center">Fruit Media Collection</h1>
      <% if !logged_in? %>
        <p class="text-center">
          <%= link_to fa_icon("sign-in") + " Log in", login_path, class: 'btn btn-xs btn-success' %> or <%= link_to fa_icon("user-plus") + " Sign Up", signup_path, class: 'btn btn-xs btn-primary' %>
          <br /> for creating your media collection
        </p>
      <% end %>
    </div>

    <div class="container">
      <%= render 'layouts/messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/create.html.erb
<h1>Pages#create</h1>
<p>Find me in app/views/pages/create.html.erb</p>

app/views/pages/destroy.html.erb
<h1>Pages#destroy</h1>
<p>Find me in app/views/pages/destroy.html.erb</p>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center" id="top-collections">All Collections</h2>
    </div>
  </div>
  <%= render 'collections/collections', obj: @collections %>

  <div align="center">
    <%= will_paginate @collections %>
  </div>
</div>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/pages/update.html.erb
<h1>Pages#update</h1>
<p>Find me in app/views/pages/update.html.erb</p>

app/views/users/_form.html.erb
<%= render 'layouts/errors', obj: @user %>

<%= form_for(@user, :html => { class: 'form-horizontal', role: 'form' }) do |f| %>
  <div class="form-group">
    <%= f.label :username, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password', autocomplite: 'off' %>
    </div>
  </div>
  <p class="text-center"><%= f.submit(@user.new_record? ? 'Sign Up' : 'Update', class: 'btn btn-success') %></p>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="well">
    <h1 class="text-center">Update your account</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 class="text-center">List of users</h1>

  <div class="row">
    <% @users.each do |user| %>
      <div class="col-md-4">
        <div class="well">
          <div class="row">
            <div class="col-md-4">
              <%= link_to gravatar_for(user, size: 80), user_path(user) %>
            </div>
            <div class="col-md-6">
              <p><%= link_to user.username, user_path(user) %></p>
              <p><%= pluralize(user.collections.count, 'collection') if user.collections %></p>
            </div>
            <% if logged_in? and current_user.admin? and current_user != user %>
              <div class="col-md-12">
                <br />
                <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are you sure? This action delete user and all collections" }, class: 'btn btn-xs btn-danger' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div align="center">
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="well">
    <h1 class="text-center">Sign up</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="text-center">User Profile <small>
    <% if logged_in? && current_user == @user %>
      <%= link_to fa_icon("pencil", text: "Edit profile"), edit_user_path(current_user) %></small>
    <% end %>
  </h1>

  <div class="well">
    <div class="row">
      <div class="col-md-2">
        <%= gravatar_for(@user, size: 160) %>
      </div>
      <div class="col-md-10">
        <h4><strong>Username: </strong><%= @user.username %></h4>
        <h4><strong>Email: </strong><%= link_to @user.email, 'mailto:' + @user.email %></h4>
        <% if logged_in? and current_user.admin? and current_user == @user %>
          <h4 class="label label-danger"><strong>Moderator</strong></h4>
        <% end %>
      </div>
    </div>
  </div>

  <% if @user_collections.count > 0 %>
    <h1 class="text-center">Collections created by <%= @user.username %></h1>
  <% end %>
  <%= render 'collections/collections', obj: @user_collections %>

  <%= will_paginate @user_collections %>
</div>